# ------------------------------------------------------------------------------
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
# ------------------------------------------------------------------------------

apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: panorama-common-hauler
build:
  local:
    push: false
    concurrency: 4
  artifacts:
    - image: panorama-common-hauler
      docker:
        buildArgs:
          HTTP_PROXY: '{{.HTTP_PROXY}}'
          HTTPS_PROXY: '{{.HTTPS_PROXY}}'
          NO_PROXY: '{{.NO_PROXY}}'
        network: host
deploy:
  kubectl:
    manifests:
      - deploy/*.yaml