apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "panorama-common-hauler.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "panorama-common-hauler.selectorLabels" . | nindent 6 }}
